# Generated by Django 3.2.8 on 2021-10-15 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_somemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SomeModel',
        ),
    ]
